version: '3.8'

services:
  db:
    image: mysql:8.3
    container_name: mysql8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mysql_network

volumes:
  db_data:

networks:
  mysql_network:

